### PR TITLE
replaced https with http

### LINKED ISSUE #203: Unable to load Certificate in the browser
While loading the certificates in my browser, I can't see the file which we have to upload, which is myCA.pem . All it shows is a localhost file certificate when I select the certificates folder for uploading. 

image

I have asked doubts in Zulip as well (in enwiki-afch stream) but didn't get any response. I would be extremely grateful if anyone can help me resolve this issue. Thanks.

### PR DESCRIPTION
**Pull request by dikshatakyar**
@enterprisey, I have changed the server.js file, and now it does not requires the upload of certificates in the browser
fixes #203

### CODE REVIEW

**Comment by enterprisey** [comment]
Works for me! Thanks.

**Comment by siddharthvp** [comment]
Thanks for filing the pull request @dikshatakyar. Next time, please always provide attribution when you copy-paste code from anywhere (https://gist.github.com/siddharthvp/d76724c8da605d5e6c679220018c5601).

It's worth noting that this changes not just https to http, but also the unbuilt JS files are now served directly, eliminating the need to run `grunt build` every time. cc @enterprisey if there are any guidelines that need to be updated elsewhere - I've updated ones within server.js itself. Build is still needed for modifications to LESS files, since those have to be compiled. (It might be worth checking if there's a fast less compiler that can do it on-the-fly.)

**Comment by enterprisey** [comment]
:/

yeah @dikshatakyar don't copy-and-paste code without attribution. I almost considered rewriting the git history to credit the proper author, but that would be grandstanding.

And yeah, I caught that change and updated documentation everywhere I could think of.

**Comment by dikshatakyar** [comment]
@enterprisey, I am extremely sorry for hurting @siddharthvp feelings. Since, majority of the newcomers were having issue with certificates so I thought of improving the code. I am sorry, I forgot to give him attribution for this.

**Comment by siddharthvp** [comment]
@dikshatakyar No hurt feelings :D. Just meant to advice you to avoid it, since larger open source projects are generally pretty serious about licensing issues, but definitely not a big deal here.

**Pull request merged**
