### PR TITLE
Handle Draft Categories

### PR DESCRIPTION
**Pull request by satcasm**
#125 
Can you please review my PR?

### CODE REVIEW

**Review by enterprisey — CHANGES_REQUESTED** [review]
I would prefer using just one .replace call with a capturing group and \1 in the replacement - the current method has a small chance it would mess with other templates.

**Comment by satcasm** [comment]
> I would prefer using just one .replace call with a capturing group and \1 in the replacement - the current method has a small chance it would mess with other templates.

I didn't get the "\1 in the replacement part".

**Comment by enterprisey** [comment]
Oops, had the syntax wrong - "xy".replace(/(\w)./, "$1z") is xz, because the $1 gets replaced with what's in the capturing group. You can use this to replace the template with what's in the middle.

**Comment by satcasm** [comment]
Hey @enterprisey , so I did some digging and came up with this:
```
text = text.replace( /(\{\{Draft categories\|\n*)((\n*\[\[:Category:\w+\]\]\n*)+)(\n*\}\})/gi, '$3' );
```
Also, in my regex test tool its showing correctly , but when I am apply it on the draft page , it not working.
Can you help me out?

**Review by enterprisey — APPROVED** [review]

**Comment by enterprisey** [comment]
Looks good, thanks again!

**Pull request merged**
